FROM node:20-slim

RUN apt-get update -y && apt-get install -y openssl

WORKDIR /app

RUN npm install -g pnpm

COPY package.json pnpm-lock.yaml ./

RUN pnpm install --frozen-lockfile

CMD ["sh", "-c", "pnpm db:push || pnpm db:deploy && pnpm dev"]
